[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
remappings = [
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", version = "1.9.5" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", version = "5.0.1" }
