[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

dependencies = ["forge-std", "openzeppelin-contracts-upgradeable"]

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.9.5" }
openzeppelin-contracts-upgradeable = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable", tag = "v5.0.1" }
